# Linear algebra

This is a lab that helps you learn linear algebra (and the related numpy commands.)  Consult Greene "Econometric Analysis" Appendix A when solving these problems.


Import appropriate packages

In [50]:
#your code here
import numpy as np
import pandas as pd
from numpy.linalg import matrix_rank as rank
from numpy.linalg import det, inv, eigvals, cond

## 1 Matrix multiplication
* create the following matrices:
a = [ 1 2 3 4], b = [5 6 7 8 ]'
(note: b includes the transpose sign)
* compute the following matrix products $a \cdot b$ and $a' \cdot b'$

In [51]:
#your code here
a = np.array([1,2,3,4]).reshape((4, 1))
b = np.array([5,6,7,8]).reshape((4, 1)).T

display(a.dot(b))
display(a.T.dot(b.T))

array([[ 5,  6,  7,  8],
       [10, 12, 14, 16],
       [15, 18, 21, 24],
       [20, 24, 28, 32]])

array([[70]])

## 2 Linear (in)dependence
Consider three vectors:
a = [1 2 3 4],
b = [5 6 7 8] and
c = [9 10 11 12]

* are these vectors linearly independent?  Calculate the rank, a related determinant, and show how they are related/unrelated

In [52]:
#your code here
x = np.arange(1, 5).reshape((4, 1))
y = np.arange(5, 9).reshape((4, 1))
z = np.arange(9, 13).reshape((4, 1))
a = np.concatenate((x, y, z), axis=1)
print(rank(a))
# print(det(a))

2


## 3 Find the inverses of the following matrices:


A = [ <br/>
    1 2 3 4 <br/>
5 6 7 8 <br/>
-1 10 11 12 <br/>
13 14 15 17 ],

B = [ <br/>
    1 0 0 <br/>
     0 4 0 <br/>
     0 0 16]

and

C = [ <br/>
    1 2 3 4 <br/>
      5 6 7 8 <br/>
      9 10 11 12 <br/>
      13 14 15 17 ]

* Check the results by left- and right multiplication of the inverse.  Explain.

In [53]:
#your code here
A = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [-1, 10, 11, 12], [13, 14, 15, 17]])
A_inverse = inv(A)
# check
result1 = A.dot(A_inverse)
display(result1)

B = np.array([[1, 0, 0], [0, 4, 0], [0, 0, 16]])
B_inverse = inv(B)
# check 
result2 = B.dot(B_inverse)
display(result2)

C = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 17]])
C_inverse = inv(C)
# check
result3 = C.dot(C_inverse)
display(result3)

array([[  1.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00],
       [  0.00000000e+00,   1.00000000e+00,   0.00000000e+00,
          0.00000000e+00],
       [  0.00000000e+00,   7.10542736e-15,   1.00000000e+00,
         -3.55271368e-15],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          1.00000000e+00]])

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

array([[  1.,   0.,   1.,   0.],
       [ -4.,   0.,  -4.,   0.],
       [ -4.,   8.,   0.,   0.],
       [  0.,  16.,   0.,   1.]])

## 4 Characteristic roots
* Find the roots (eigenvalues) of the matrices A, B, C above.
* Calculate the condition numbers of these matrices in two ways: the default numpy way, and in this way as it is explained in Greene (2003, page 829)
* Explain the results

In [54]:
#your code here
A_eig = eigvals(A)
B_eig = eigvals(B)
C_eig = eigvals(C)
# condition number
a = cond(A)
b = cond(B)
c = cond(C)

print(a, b, c)

299.050204082 16.0 7.60469682786e+16
